sudo: required
language: ruby
rvm:
  - 2.3.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install librsync-dev -y
  - gem install bundler -v 1.12.5
install:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake compile
