sudo: required
language: ruby
rvm:
  - 2.3.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential cmake libpopt-dev libbz2-dev -y
  - wget https://github.com/librsync/librsync/archive/v1.0.1.tar.gz
  - tar -xzvf v1.0.1.tar.gz
  - cd librsync-1.0.1 && cmake . && make && sudo make install
  - gem install bundler -v 1.12.5
install:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake compile
